DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS requests;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
                                     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                     name VARCHAR(255) NOT NULL,
                                     email VARCHAR(512) NOT NULL,
                                     UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests (
                                     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                     description VARCHAR(255) NOT NULL,
                                     requestor_id INTEGER REFERENCES users(id),
                                     created TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS items (
                                     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                     name VARCHAR(255) NOT NULL,
                                     description VARCHAR(255) NOT NULL,
                                     is_available BOOLEAN NOT NULL,
                                     owner_id INTEGER REFERENCES users(id),
                                     request_id INTEGER REFERENCES requests(id)
);

CREATE TABLE IF NOT EXISTS bookings (
                                     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                     start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                     end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                     item_id INTEGER REFERENCES items(id),
                                     booker_id INTEGER REFERENCES users(id),
                                     status VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS comments (
                                     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                     text VARCHAR(255) NOT NULL,
                                     item_id INTEGER REFERENCES items(id),
                                     author_id INTEGER REFERENCES users(id),
                                     created TIMESTAMP WITHOUT TIME ZONE NOT NULL
);